In [ ]:
!gsutil ls gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023

gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023/metadata_GuptaLab+553d1bd5+2023-04-30-18h-23m-30s.json
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023/trajectory.h5
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023/trajectory_im128.h5
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023/recordings/


In [ ]:
!gsutil ls gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/

gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/metadata_GuptaLab+553d1bd5+2023-04-20-14h-28m-23s.json
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/trajectory.h5
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/trajectory_im128.h5
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/


In [ ]:
!gsutil ls gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-07-08/Sat_Jul__8_10:49:28_2023/recordings/SVO

gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-07-08/Sat_Jul__8_10:49:28_2023/recordings/SVO/18026681.svo
gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-07-08/Sat_Jul__8_10:49:28_2023/recordings/SVO/22008760.svo
gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-07-08/Sat_Jul__8_10:49:28_2023/recordings/SVO/24400334.svo


In [ ]:
!gsutil cat gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-07-09/Sun_Jul__9_18:59:44_2023/metadata_GuptaLab+553d1bd5+2023-07-09-18h-59m-44s.json

{"uuid": "GuptaLab+553d1bd5+2023-07-09-18h-59m-44s", "lab": "GuptaLab", "user": "Mohan Kumar", "user_id": "553d1bd5", "date": "2023-07-09", "timestamp": "2023-07-09-18h-59m-44s", "hdf5_path": "success/2023-07-09/Sun_Jul__9_18:59:44_2023/trajectory.h5", "building": "Smith Hall 121", "scene_id": 500180237, "success": true, "robot_serial": "panda-295341-1325237", "r2d2_version": "1.3", "current_task": "Move object into or out of container (ex: drawer, clothes hamper, plate, trashcan, washer)", "trajectory_length": 668, "wrist_cam_serial": "16291792", "ext1_cam_serial": "22246076", "ext2_cam_serial": "26638268", "wrist_cam_extrinsics": [0.38476760593776255, -0.003948729810592848, 0.5165126234498831, 2.7075348819976526, 0.04361013913601752, 1.6120851055998053], "ext1_cam_extrinsics": [-0.17238707747361265, 0.8769851356846587, 0.6402230222978303, -2.016203625251342, -0.14133446426244434, -2.1535101463892876], "ext2_cam_extrinsics": [-0.09266930443312493, -0.6728005528752469, 0.72551227125146

In [ ]:
%cd /content

/content


In [ ]:
!mkdir store_data

In [ ]:
!gsutil cat gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-06-18

CommandException: No URLs matched: gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-06-18


In [ ]:
!gsutil cat gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-06-18/Sun_Jun_18_21:19:59_2023/metadata_GuptaLab+553d1bd5+2023-06-18-21h-19m-59s.json

{"uuid": "GuptaLab+553d1bd5+2023-06-18-21h-19m-59s", "lab": "GuptaLab", "user": "Mohan Kumar", "user_id": "553d1bd5", "date": "2023-06-18", "timestamp": "2023-06-18-21h-19m-59s", "hdf5_path": "success/2023-06-18/Sun_Jun_18_21:19:59_2023/trajectory.h5", "building": "Smith Hall Fetch Lab", "scene_id": 5235850418, "success": true, "robot_serial": "295341-1325237", "r2d2_version": "1.1", "current_task": "Open or close slidable objects (ex: toaster, drawers, sliding doors, dressers)", "trajectory_length": 71, "wrist_cam_serial": "16291792", "ext1_cam_serial": "22246076", "ext2_cam_serial": "26638268", "wrist_cam_extrinsics": [0.21885381960889255, -0.1423664457067457, 0.5268558746424304, 2.5341523292697015, 0.16268025844624878, 1.5880563561609717], "ext1_cam_extrinsics": [0.06126845421106433, 0.4951337668615451, 0.6651930769671347, -1.5755163454721475, 0.009724033533159426, -2.1473608246676887], "ext2_cam_extrinsics": [-0.17495316663380056, -0.5501611345841874, 0.7400616933701863, -1.8397329

In [ ]:
gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/metadata_AUTOLab+5d05c5aa+2023-08-12-16h-26m-07s.json /content/store_data!gsutil -m cp -r

Copying gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/metadata_AUTOLab+5d05c5aa+2023-08-12-16h-26m-07s.json...
/ [1/1 files][  1.7 KiB/  1.7 KiB] 100% Done                                    
Operation completed over 1 objects/1.7 KiB.                                      


In [ ]:
!gsutil ls gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO

gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO/16291792.svo
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO/22246076.svo
gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO/26638268.svo


In [ ]:
!mkdir store_svo

In [ ]:
# !gsutil cp gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-05-19/Fri_May_19_10:56:04_2023/recordings/SVO/16291792.svo /content/store_svo/
!gsutil cp -r gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/recordings/ /content/store_svo/
# !gsutil cp gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-05-19/Fri_May_19_10:56:04_2023/recordings/SVO/26638268.svo /content/store_svo/


Copying gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/recordings/MP4/18026681-stereo.mp4...
Copying gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/recordings/MP4/18026681.mp4...
Copying gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/recordings/MP4/22008760-stereo.mp4...
Copying gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/recordings/MP4/22008760.mp4...
\ [4 files][ 38.0 MiB/ 38.0 MiB]                                                
==> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m cp ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.

Copying gs://gresearch/robotics/droid_raw/1.0.1/AUTOLab/success/2023-08-12/Sat_Aug_12_16:26:07_2023/recordings/MP4/24400334-stere

**Uses the path in the json and saved the videoes in a separate folder ```videos```**



In [ ]:
import requests
import json
import os

json_data = '''
{"uuid": "GuptaLab+553d1bd5+2023-04-20-14h-28m-23s", "lab": "GuptaLab", "user": "Mohan Kumar", "user_id": "553d1bd5", "date": "2023-04-20", "timestamp": "2023-04-20-14h-28m-23s", "hdf5_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/trajectory.h5", "building": "Smith Hall Fetch Lab", "scene_id": 9934859632, "success": true, "robot_serial": "295341-1325237", "r2d2_version": "1.1", "current_task": "Move object into or out of container (ex: drawer, clothes hamper, plate, trashcan, washer)", "trajectory_length": 140, "wrist_cam_serial": "16291792", "ext1_cam_serial": "22246076", "ext2_cam_serial": "26638268", "wrist_cam_extrinsics": [0.3285869949117049, -0.15715476236411358, 0.46288779311683903, 2.7719949090115916, -0.1105557217271218, 1.6783419952083678], "ext1_cam_extrinsics": [0.0625700860308161, 0.7849934078474259, 0.41321386028430906, -1.620310649739649, 0.0378335771770526, -2.5025320852316324], "ext2_cam_extrinsics": [-0.08435779304506942, -0.4948429152974599, 0.48183883314683706, -1.583088257034475, -0.04749638364740649, -1.0785179926740802], "wrist_svo_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO/16291792.svo", "wrist_mp4_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/MP4/16291792.mp4", "ext1_svo_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO/22246076.svo", "ext1_mp4_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/MP4/22246076.mp4", "ext2_svo_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/SVO/26638268.svo", "ext2_mp4_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/MP4/26638268.mp4", "left_mp4_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/MP4/22246076.mp4", "right_mp4_path": "success/2023-04-20/Thu_Apr_20_14:28:23_2023/recordings/MP4/26638268.mp4"}'''

data = json.loads(json_data)

videos_folder = 'videos'
if not os.path.exists(videos_folder):
    os.makedirs(videos_folder)

video_mappings = {
    data['wrist_mp4_path']: 'wrist_arm.mp4',
    data['ext1_mp4_path']: 'ext1_arm.mp4',
    data['ext2_mp4_path']: 'ext2_arm.mp4',
    data['left_mp4_path']: 'left_arm.mp4',
    data['right_mp4_path']: 'right_arm.mp4'
}

for url, new_filename in video_mappings.items():
    gcs_url = f"https://storage.googleapis.com/gresearch/robotics/droid_raw/1.0.1/GuptaLab/{url}"
    r = requests.get(gcs_url, stream=True)
    download_path = os.path.join(videos_folder, new_filename)
    with open(download_path, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024):
            if chunk:
                f.write(chunk)
    print(f"Downloaded {new_filename} to {videos_folder}")




---

In [ ]:
!pip install tensorflow-datasets


In [ ]:
import tensorflow_datasets as tfds
ds = tfds.load("droid_100", data_dir="gs://gresearch/robotics", split="train")

In [ ]:
for example in ds:
    # Access the episode_metadata
    episode_metadata = example['episode_metadata']

    # Print the episode_metadata
    print("Episode Metadata:")
    print(episode_metadata)
    print()
    break

Episode Metadata:
{'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/nfs/kun2/datasets/r2d2/r2d2-data-full/RAIL/success/2023-04-17/Mon_Apr_17_14:48:05_2023/trajectory.h5'>, 'recording_folderpath': <tf.Tensor: shape=(), dtype=string, numpy=b'/nfs/kun2/datasets/r2d2/r2d2-data-full/RAIL/success/2023-04-17/Mon_Apr_17_14:48:05_2023/recordings/MP4'>}



In [ ]:
import tensorflow_datasets as tfds
import numpy as np
from PIL import Image
import os

# Create a directory to save images
output_dir = "/content/extracted_images_2"
os.makedirs(output_dir, exist_ok=True)

# Load the dataset
ds = tfds.load("droid_100", data_dir="gs://gresearch/robotics", split="train")

# Iterate through the dataset and save only exterior_image_1_left
for episode in ds.shuffle(10, seed=0).take(1):
    for i, step in enumerate(episode["steps"]):
        # Get the exterior_image_1_left and convert it to a numpy array
        image_array = step["observation"]["exterior_image_1_left"].numpy()

        # Convert the numpy array to a PIL image
        image = Image.fromarray(image_array)

        # Save the image as a PNG file
        image.save(os.path.join(output_dir, f"image_{i:04d}.png"))

print(f"Images saved in '{output_dir}' directory.")


Images saved in '/content/extracted_images_2' directory.


In [ ]:
import shutil

# Path to the folder containing the images
folder_to_zip = output_dir
zip_filename = "/content/extracted_images_2.zip"

# Create a zip file of the folder
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', folder_to_zip)

print(f"Images zipped and saved as {zip_filename}.")


Images zipped and saved as /content/extracted_images_2.zip.


---


In [ ]:
!pip install h5py


In [ ]:
!gsutil -m cp -r gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023/trajectory.h5 /content/

Copying gs://gresearch/robotics/droid_raw/1.0.1/GuptaLab/success/2023-04-30/Sun_Apr_30_18:23:30_2023/trajectory.h5...
/ [1/1 files][990.8 KiB/990.8 KiB] 100% Done                                    
Operation completed over 1 objects/990.8 KiB.                                    


In [ ]:
import h5py

file_path = '/content/trajectory.h5'

hdf5_file = h5py.File(file_path, 'r')

def print_hdf5_contents(name, obj):
    print(name, obj)

print("Contents of HDF5 file:")
hdf5_file.visititems(print_hdf5_contents)

# # # # 22246076 -> cam ID

# cam_2246076 = hdf5_file['observation/camera_extrinsics/22246076_left']

# # print(f"HDF5 dataset 'camera 22256076': shape {cam_2246076.shape}, type {cam_2246076.dtype}")

# print("Camera Extrinsics data:")
# print(len(cam_2246076))


Contents of HDF5 file:
action <HDF5 group "/action" (9 members)>
action/cartesian_position <HDF5 dataset "cartesian_position": shape (140, 6), type "<f8">
action/cartesian_velocity <HDF5 dataset "cartesian_velocity": shape (140, 6), type "<f8">
action/gripper_position <HDF5 dataset "gripper_position": shape (140,), type "<f8">
action/gripper_velocity <HDF5 dataset "gripper_velocity": shape (140,), type "<f8">
action/joint_position <HDF5 dataset "joint_position": shape (140, 7), type "<f8">
action/joint_velocity <HDF5 dataset "joint_velocity": shape (140, 7), type "<f8">
action/robot_state <HDF5 group "/action/robot_state" (10 members)>
action/robot_state/cartesian_position <HDF5 dataset "cartesian_position": shape (140, 6), type "<f8">
action/robot_state/gripper_position <HDF5 dataset "gripper_position": shape (140,), type "<f8">
action/robot_state/joint_positions <HDF5 dataset "joint_positions": shape (140, 7), type "<f8">
action/robot_state/joint_torques_computed <HDF5 dataset "joint


**Saving cartesian positions in a txt file**


In [ ]:
import h5py
import numpy as np

file_path = '/content/trajectory.h5'
hdf5_file = h5py.File(file_path, 'r')

cartesian_position = hdf5_file['action/cartesian_position']

print(f"HDF5 dataset 'cartesian_position': shape {cartesian_position.shape}, type {cartesian_position.dtype}")

print("Cartesian position data:")
print(cartesian_position[:])

output_file = 'cart_pos.txt'
np.savetxt(output_file, cartesian_position, fmt='%.6f', delimiter=', ')

hdf5_file.close()

print(f"Cartesian positions saved to {output_file}")


HDF5 dataset 'cartesian_position': shape (226, 6), type float64
Cartesian position data:
[[ 0.30208537 -0.10953411  0.46826899 -2.95463891  0.01949048  0.22504561]
 [ 0.30226141 -0.10981972  0.46957517 -2.9558794   0.01668902  0.22457779]
 [ 0.30217764 -0.10990722  0.47020161 -2.95642075  0.01504828  0.22440879]
 ...
 [ 0.42024055 -0.06298461  0.44569331  3.06055968 -0.43866336 -0.60407019]
 [ 0.42018235 -0.06321672  0.44565478  3.06050071 -0.43860399 -0.60532667]
 [ 0.42014733 -0.06337299  0.44563878  3.06062346 -0.43855235 -0.60632568]]
Cartesian positions saved to cart_pos.txt


In [ ]:
import h5py
import numpy as np

file_path = '/content/trajectory.h5'
hdf5_file = h5py.File(file_path, 'r')

cartesian_position = hdf5_file['action/joint_position']

# print(f"HDF5 dataset 'cartesian_position': shape {cartesian_position.shape}, type {cartesian_position.dtype}")

print("Cartesian position data:")
print(cartesian_position[:])

output_file = 'joint_pos.txt'
np.savetxt(output_file, cartesian_position, fmt='%.6f', delimiter=', ')

hdf5_file.close()

print(f"Cartesian positions saved to {output_file}")


Cartesian position data:
[[-5.39881010e-02 -4.77734066e-01  9.67529584e-02 -2.24699887e+00
  -1.43608536e-01  1.62009636e+00  2.72758799e-01]
 [-5.39729986e-02 -4.77901685e-01  9.67750959e-02 -2.24697715e+00
  -1.43625476e-01  1.62008939e+00  2.72760107e-01]
 [-5.39843068e-02 -4.78161079e-01  9.67825959e-02 -2.24695445e+00
  -1.43636824e-01  1.62008902e+00  2.72762379e-01]
 [-5.39757926e-02 -4.78139073e-01  9.67912581e-02 -2.24696335e+00
  -1.43646069e-01  1.62008850e+00  2.72759731e-01]
 [-5.39828036e-02 -4.78146683e-01  9.67859849e-02 -2.24696496e+00
  -1.43650184e-01  1.62008687e+00  2.72762106e-01]
 [-5.39784506e-02 -4.78150066e-01  9.67980754e-02 -2.24696272e+00
  -1.43655690e-01  1.62008892e+00  2.72763829e-01]
 [-5.39752040e-02 -4.78158640e-01  9.68018128e-02 -2.24696070e+00
  -1.43660994e-01  1.62008882e+00  2.72768642e-01]
 [-5.39802909e-02 -4.78132375e-01  9.67963533e-02 -2.24696506e+00
  -1.43666368e-01  1.62008758e+00  2.72763085e-01]
 [-5.39661255e-02 -4.78167234e-01  9.68

In [ ]:

import h5py
import numpy as np

file_path = '/content/trajectory.h5'
hdf5_file = h5py.File(file_path, 'r')

cartesian_position = hdf5_file['action/gripper_position']

# print(f"HDF5 dataset 'cartesian_position': shape {cartesian_position.shape}, type {cartesian_position.dtype}")

print("Cartesian position data:")
print(cartesian_position[:])

# output_file = 'joint_pos.txt'
# np.savetxt(output_file, cartesian_position, fmt='%.6f', delimiter=', ')

# hdf5_file.close()

# print(f"Cartesian positions saved to {output_file}")


Cartesian position data:
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.03608025 0.19197009 0.28083699 0.30286345 0.37334804 0.47466963
 0.54955949 0.62885461 0.69493394 0.75660792 0.83590309 0.8931718
 0.9636564  0.99

**Getting the camera extrinsics**

In [ ]:
print(len(cam_2246076))
print(cartesian_position.shape[0])

96
96


In [ ]:
import h5py


file_path = '/content/trajectory.h5'

hdf5_file = h5py.File(file_path, 'r')

dataset_paths = [
    'observation/camera_extrinsics/19824535_left',
    'observation/camera_extrinsics/19824535_right',
    'observation/camera_extrinsics/22246076_left',
    'observation/camera_extrinsics/22246076_right',
    'observation/camera_extrinsics/23404442_left',
    'observation/camera_extrinsics/23404442_right'
]

for dataset_path in dataset_paths:
    dataset = hdf5_file[dataset_path]
    print(f"HDF5 dataset '{dataset_path}': shape {dataset.shape}, type {dataset.dtype}")
    print("Data:")
    print(dataset[:1])

hdf5_file.close()


HDF5 dataset 'observation/camera_extrinsics/19824535_left': shape (140, 6), type float64
Data:
[[-0.07176023  0.03024986  0.02164358 -0.3201233   0.01153831 -1.55427397]]
HDF5 dataset 'observation/camera_extrinsics/19824535_right': shape (140, 6), type float64
Data:
[[-0.07209364 -0.03281814  0.01799876 -0.32436696  0.00983603 -1.55377928]]
HDF5 dataset 'observation/camera_extrinsics/22246076_left': shape (140, 6), type float64
Data:
[[ 0.06257009  0.78499341  0.41321386 -1.62031065  0.03783358 -2.50253209]]
HDF5 dataset 'observation/camera_extrinsics/22246076_right': shape (140, 6), type float64
Data:
[[-0.03345576  0.71726764  0.40275558 -1.60782832  0.0319634  -2.4994542 ]]
HDF5 dataset 'observation/camera_extrinsics/23404442_left': shape (140, 6), type float64
Data:
[[ 0.27212357 -0.56289947  0.57829605 -2.04916225 -0.00867735 -0.46446894]]
HDF5 dataset 'observation/camera_extrinsics/23404442_right': shape (140, 6), type float64
Data:
[[ 0.3819312  -0.61567944  0.5789578  -2.048677

In [ ]:
import os
import h5py
from PIL import Image

# Path to the HDF5 file
file_path = '/content/trajectory.h5'

import h5py

file_path = '/content/trajectory.h5'

with h5py.File(file_path, 'r') as hdf5_file:
    def print_structure(name, obj):
        print(name)
    hdf5_file.visititems(print_structure)


# # Open the HDF5 file
# with h5py.File(file_path, 'r') as hdf5_file:
#     # Access image datasets
#     exterior_image_1 = hdf5_file["steps/observation/exterior_image_1_left"][:]

#     # Create directories to save images
#     output_dir = "exterior_images"
#     os.makedirs(f"{output_dir}/exterior_image_1_left", exist_ok=True)

#     # Save exterior_image_1_left images
#     for idx, image_array in enumerate(exterior_image_1):
#         image = Image.fromarray(image_array)
#         image.save(f"{output_dir}/exterior_image_1_left/image_{idx:04d}.png")

# print(f"Images saved in '{output_dir}' directory.")


action
action/cartesian_position
action/cartesian_velocity
action/gripper_position
action/gripper_velocity
action/joint_position
action/joint_velocity
action/robot_state
action/robot_state/cartesian_position
action/robot_state/gripper_position
action/robot_state/joint_positions
action/robot_state/joint_torques_computed
action/robot_state/joint_velocities
action/robot_state/motor_torques_measured
action/robot_state/prev_command_successful
action/robot_state/prev_controller_latency_ms
action/robot_state/prev_joint_torques_computed
action/robot_state/prev_joint_torques_computed_safened
action/target_cartesian_position
action/target_gripper_position
observation
observation/camera_extrinsics
observation/camera_extrinsics/16291792_left
observation/camera_extrinsics/16291792_left_gripper_offset
observation/camera_extrinsics/16291792_right
observation/camera_extrinsics/16291792_right_gripper_offset
observation/camera_extrinsics/19824535_left
observation/camera_extrinsics/19824535_right
observa